application: yinzbot
version: 5
runtime: python27
# Apparently this is required to use python27
threadsafe: false
api_version: 1

handlers:
- url: /twitterbot/bot
  script: bot.app
- url: /twitterbot/follow
  script: follow.app
